### ISSUE TITLE
Model Points for class/struct?

### ISSUE THREAD

**Issue by peterus** [johnttaylor/pim#15]
Thanks for the book! I love it! Got the recommendation from the podcast "The Agile Embedded Podcast".

How do I handle class/struct's which are holding some data which is bound together?

As an example: data from a GPS? like latitude, longitude, high, etc.
I would put them into one class as I dont want to have multiple different Model Points.

**Comment by johnttaylor** [comment]
Creating new model point types is fairly simple for a data struct.  Things get a more complicated when the top level type is array.  Just to point out - a model point contains _just_ data, i.e. not intended to contain a class (i.e. data + behavior).

If you look in the [src/Storm/Dm](https://github.com/johnttaylor/pim/tree/master/src/Storm/Dm) you find several examples of how create a model point type for an underlying data structure.  Somethings to note:
1. At minimum you should provide type specific read()/write() methods that take a reference to the data structure
2. Provide additional atomic read, write, read-modify-write operations as needed by your application.  For example if you just want to read a single field within the data struct - you would have a new MP method that reads the entire data struct and then returns the single/desired value.  For a corresponding write operation that only updates a single field within the struct - the implementation would be to atomically: 1) read the current MP value into a local variable, 2) modify the single field in the local instance, then 3) update the entire data structure.  The above mentioned code provides several examples of this.
3. If you do provide additional write methods (beside writing the entire struct) - you will need to decide what it means when you do a 'partial' write when the MP is in the invalid state.  This is because if you are doing 'partial' write - you are missing valid values for the other bits.  The recommendation is for this scenario set the entire data struct to zero or some other defaults.  This provides - at a minimum - consisted (albeit not always perfect) behavior for this use case.  Setting the default values can be done in the `hookSetInvalid()` method of the new MP class.
4. The tedious part of building a new MP type for a data structure is implementing the `fromJSON_()` and `setJSONVal()` methods.  Even if you don't plan on using the JSON serialize functionality - I strongly recommend that you __don't__ skip this part of the implementation.  At a minimum the JSON serialization is used for being able to read/write Model Points via the TShell/Debug console.
5. Also, I recommended to provide a unit test for you new Model Point type(s).  For this - start with an existing MP unit test that is the most similar to your new type.

Let me know if this answered your question, made things worse ;-), or created new questions.

**Comment by johnttaylor** [comment]
Peter,

FYI - I did reply to your question, but I responded on the repo's GitHub
issue page.  It is unclear to me if you received an email notification when
I updated the issue you opened.  I apologize for any delays.

-john
