### ISSUE TITLE
How do I override the compiler in the build system?

### ISSUE THREAD

**Issue by phillipjohnston** [johnttaylor/pim#6]
For example, gcc is installed on my system as "gcc-11", so I want to reference that instead of the default assumption of the name.

**Comment by johnttaylor** [comment]
The nqbp build scripts for gcc builds under Linux assume 'gcc' is in the command path and the it is version you want.  Other nqbp build scripts for different compilers do not work this way, i.e. this is something that can be fixed/changed.  I will put together a fix to the linux/gcc build scripts so that it will default to the gcc in the command path, but support an option specify a specific path to the compiler toolchain.  I will follow-up once I have fix/change available.

In the interim the work-around would be to update your command path (for a given terminal instance) so that it puts the version/instance of the GCC toolchain you want to use before the system's default GCC toolchain.

**Comment by phillipjohnston** [comment]
> In the interim the work-around would be to update your command path (for a given terminal instance) so that it puts the version/instance of the GCC toolchain you want to use before the system's default GCC toolchain.

Just to clarify, what I mean is that all the binaries for the toolchains are suffixed with the major version (gcc-11, gcc-10, gcc-9, etc.). I do a lot of compiler variant testing for some of our open-source projects, so they are generally available.

I don't think this is something to overhaul your build system for my specific use case.

**Comment by johnttaylor** [comment]
This has been resolved in commit [22c1e68](https://github.com/johnttaylor/pim/commit/22c1e68c8045d3fd5dad0f1ee023ec5d0abc67eb)
